name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        **ALPHA SOFTWARE WARNING**
        Chisel is currently in alpha. Many features use mock implementations for testing.
        Please check the [roadmap](https://github.com/ataiva-software/chisel#implementation-status) before reporting issues.

  - type: input
    id: version
    attributes:
      label: Chisel Version
      description: What version of Chisel are you running?
      placeholder: v0.1.0-alpha
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please paste relevant configuration files (module.yaml, inventory.yaml, etc.)
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any relevant log output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
