apiVersion: ataiva.com/forge/v1
kind: Module
metadata:
  name: enterprise-web-server
  version: 1.0.0
  description: CIS-compliant web server configuration for production
  labels:
    environment: production
    compliance: cis-ubuntu-20.04
    team: platform
    criticality: high
spec:
  resources:
    # CIS 6.1.2 - Ensure permissions on /etc/passwd are configured
    - type: file
      name: passwd-permissions
      state: present
      properties:
        path: /etc/passwd
        mode: "0644"
        owner: root
        group: root

    # CIS 6.1.3 - Ensure permissions on /etc/shadow are configured  
    - type: file
      name: shadow-permissions
      state: present
      properties:
        path: /etc/shadow
        mode: "0640"
        owner: root
        group: shadow

    # Install required packages
    - type: pkg
      name: nginx
      state: present

    - type: pkg
      name: auditd
      state: present

    # NIST AU-2 - Audit Events (auditd service must be enabled)
    - type: service
      name: auditd
      state: running
      properties:
        enabled: true

    # Configure nginx service
    - type: service
      name: nginx
      state: running
      properties:
        enabled: true

    # Secure nginx configuration
    - type: file
      name: nginx-config
      state: present
      properties:
        path: /etc/nginx/sites-available/default
        mode: "0644"
        owner: root
        group: root
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              
              # Security headers
              add_header X-Frame-Options DENY;
              add_header X-Content-Type-Options nosniff;
              add_header X-XSS-Protection "1; mode=block";
              
              root /var/www/html;
              index index.html index.htm index.nginx-debian.html;
              
              server_name _;
              
              location / {
                  try_files $uri $uri/ =404;
              }
              
              # Hide nginx version
              server_tokens off;
          }

    # Create secure web directory
    - type: file
      name: web-directory
      state: present
      properties:
        path: /var/www/html
        file_type: directory
        mode: "0755"
        owner: www-data
        group: www-data

    # Create audit configuration
    - type: file
      name: audit-config
      state: present
      properties:
        path: /etc/audit/auditd.conf
        mode: "0640"
        owner: root
        group: root
        content: |
          # Audit daemon configuration
          log_file = /var/log/audit/audit.log
          log_format = RAW
          log_group = adm
          priority_boost = 4
          flush = INCREMENTAL_ASYNC
          freq = 50
          num_logs = 5
          disp_qos = lossy
          dispatcher = /sbin/audispd
          name_format = NONE
          max_log_file = 8
          max_log_file_action = ROTATE
          space_left = 75
          space_left_action = SYSLOG
          admin_space_left = 50
          admin_space_left_action = SUSPEND
          disk_full_action = SUSPEND
          disk_error_action = SUSPEND

    # Ensure system accounts are secured (CIS 5.4.2)
    - type: user
      name: nginx-user
      state: present
      properties:
        system: true
        shell: /usr/sbin/nologin
        home: /var/www
        create_home: false

    # Create log rotation for audit logs
    - type: file
      name: audit-logrotate
      state: present
      properties:
        path: /etc/logrotate.d/audit
        mode: "0644"
        owner: root
        group: root
        content: |
          /var/log/audit/*.log {
              weekly
              rotate 52
              compress
              delaycompress
              missingok
              create 0640 root adm
              postrotate
                  /sbin/service auditd restart > /dev/null 2>&1 || true
              endscript
          }
